apiVersion: kustomize.toolkit.fluxcd.io/v1 # FluxCD kustomize-controller
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure # Path to the directory containing the kustomization.yaml file to be applied
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age