apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          image: xutyxd/xuty.dev:1.1.0  # {"$imagepolicy": "flux-system:xuty-dev"}