apiVersion: v1
data:
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:OPEwOePcit5KG8gEQ7Ntd6fjAmS+D+8kmKSCPh1ZQ3s4yuapXPa1blE6zh5ieOEWqss1lPuo6YRWIjfHxg9l5bzsGAdThrTJdiBmNXzi9XrpcZh+XEVvRGUDMV55Ht7lU7/zOH6x2AR3Dr0GyC+TgRccwrRFu6bpTOCPzeL0orFYP14qBsnOw6nwCM+/3n8lgyD1SBO+xgQASfoWtGGt3RzSqR+t3x2jkPJZOSy7OZsfwFU6pAgvvDWJmM5nPPey8fZ4GbSXr0XA9I9Jok95qU0xame5NqNBlHkvI1r2ePsS3emXqAONMBfKivrHnfncQvnPT5ea/tU=,iv:TJ3f9GJsHDV3eGgiEH8tpXI/ITU/kkRhuhgljTswCqU=,tag:PWtiLRbsxq9rFPzVDKaolg==,type:str]
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQUJ2RGQ0L0RTQm1pMUdD
            aUY2NWxHbUphcVRoZFJqQXh3ZDEyVWk4ajNRCjNpNXZkcXRuVmIwcUxpR1J1MmR1
            QmpUV3ptSVhnZVU5TFNnbkI3ZVpvRGcKLS0tIEZvNlovSzlHMmhuVVcwd2tPVS9D
            aVU0YlRFbEFwOG9NMGJPdVp6WHdMRncK9tvaqdHjcYiSrwd/QuAneHn9ijOKNSZL
            R4XTeqDxlfawUjsDScR+j/8wc1bgB78Le2zhkZfYsQbDZyUGaf/W9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12elxr2k3yy0xyjzq4sm0zeln5cz5xqk6vs6achwp7tsnqe73yfrsmvnh76
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T19:17:49Z"
    mac: ENC[AES256_GCM,data:JV10z/sbdzRQ6anixwYL5YtExFvc9g1uBCg8aUm6D6eJgYEh8ndMMj17pjOhSrXeZOpPLWOrvqGDKSQLj7+bGefAOhD1xwLi+auzFVfhuQ1brFrllrYfWXjpLLlgbzl9GyZA8wFma/T3U/V1HrJfQxy4NPFcTitlBbXtarr6BDA=,iv:U/joA33XREd+bkw9B0KZGiulm0WUY7RdxgoydccHci0=,tag:baLkZiw6CbN5MzjoYRW0TA==,type:str]
    version: 3.13.2
