apiVersion: v1
data:
    password: ENC[AES256_GCM,data:UR3nDw8QY43mF12ozpo+zq3/hLKhlibrcBLibd+HJB8XNE9/4wN5xCwMB/uepdAo3f361GPHwGKCj5GGPLpBFJ2CPWyuNPYK/jfKRt2yGV2tQAWUuNYKOfdguxy3Z/4AJGTVeAoSohcwwuXeh+xsZwB5gdsL4Kh2iTAV/g==,iv:Z+AN05ZGuAvqQx6WKMN+mI7t7qVU7lgi9aW8j6Ww18E=,tag:57N0oQ8xm5/LVEz7S2Y6jQ==,type:str]
    username: ENC[AES256_GCM,data:loIB/k0E834=,iv:Dcl5GyiSiN8NSAGfLbRf0plilJ890ym8Rj3fnHbnVog=,tag:I7hn9Ov3OuxsflAvYyoGww==,type:str]
kind: Secret
metadata:
    name: github-pat
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZTBDRmpuZXMzZCswbDNa
            ZURJN3FUSjFlV0R1c2F3Q2wwL0dWd0NIRDA4CjJ5ZytnRUhmWEtHZHJoSm9jUlNp
            djRhd05pc0s0MkZDZU9zUXM4N2NaM0kKLS0tIDhSWEh6TnZDNTc0MVhmcys2MGl6
            UGwwakM5WGkzUGVSZFFJb0E1WSszeEUKLnJZdZBfiN3mZ6zHkhsEX+bAjT7e8K4q
            0zLRrKQ7HipKj/AYUXvQ73ouEiQcuVCgfrqo/sdNtkDN4qwIYySFDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12elxr2k3yy0xyjzq4sm0zeln5cz5xqk6vs6achwp7tsnqe73yfrsmvnh76
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T17:26:52Z"
    mac: ENC[AES256_GCM,data:KB4cA/IbqeVb6H+6BddDqVynFUGZN9UPBjnSABZWiQMk8VmU1dsPEB/Ao0N4Wd/o9LFx9NqjXgXy8Dps/NU5uzJsN59tDfjlSCv+6jZXXKCzEZKttNtpD3ndfD3jXZymHhsfBvwSVyOIwuJehVJGj6QdZzCHGNtATAP/QYaXgIE=,iv:h42M03dZ0J/ZbYubE+lRBZ4kYwgHbL4+F6zs3A+YPmA=,tag:GEmACcgdC0Q78HH7W1RsaQ==,type:str]
    version: 3.13.2
